import type {
  Lead,
  Client,
  Policy,
  Appointment,
  Task,
  Carrier,
  Commission,
  KPIData,
} from './types';

export const mockKPIs: KPIData = {
  totalLeads: 142,
  appointmentsToday: 5,
  policiesWritten: 28,
  monthlyPremium: 14820,
  monthlyCommissions: 6540,
  pendingTasks: 12,
};

export const mockLeads: Lead[] = [
  {
    id: 'l1',
    firstName: 'Robert',
    lastName: 'Johnson',
    email: 'rjohnson@email.com',
    phone: '(555) 234-5678',
    status: 'qualified',
    source: 'Facebook Ad',
    tags: ['final_expense', 'senior'],
    notes: 'Interested in Final Expense coverage. Has existing whole life policy.',
    assignedTo: 'Courtney K.',
    createdAt: '2026-06-20',
    updatedAt: '2026-06-28',
    age: 67,
    state: 'TX',
    city: 'Houston',
  },
  {
    id: 'l2',
    firstName: 'Maria',
    lastName: 'Santos',
    email: 'msantos@email.com',
    phone: '(555) 345-6789',
    status: 'proposal',
    source: 'Referral',
    tags: ['mortgage_protection', 'homeowner'],
    notes: 'Recently purchased home. Looking for mortgage protection.',
    assignedTo: 'Courtney K.',
    createdAt: '2026-06-22',
    updatedAt: '2026-06-29',
    age: 42,
    state: 'FL',
    city: 'Orlando',
  },
  {
    id: 'l3',
    firstName: 'James',
    lastName: 'Williams',
    email: 'jwilliams@email.com',
    phone: '(555) 456-7890',
    status: 'new',
    source: 'Direct Mail',
    tags: ['term', 'family'],
    notes: 'Family of 4. Looking for term coverage.',
    assignedTo: 'Courtney K.',
    createdAt: '2026-06-29',
    updatedAt: '2026-06-29',
    age: 35,
    state: 'GA',
    city: 'Atlanta',
  },
  {
    id: 'l4',
    firstName: 'Dorothy',
    lastName: 'Brown',
    email: 'dbrown@email.com',
    phone: '(555) 567-8901',
    status: 'contacted',
    source: 'Google Ad',
    tags: ['final_expense', 'senior'],
    notes: 'Retired. Fixed income. Looking for affordable burial coverage.',
    assignedTo: 'Courtney K.',
    createdAt: '2026-06-25',
    updatedAt: '2026-06-27',
    age: 72,
    state: 'OH',
    city: 'Columbus',
  },
  {
    id: 'l5',
    firstName: 'Michael',
    lastName: 'Davis',
    email: 'mdavis@email.com',
    phone: '(555) 678-9012',
    status: 'negotiation',
    source: 'Referral',
    tags: ['whole_life', 'business_owner'],
    notes: 'Business owner. Wants whole life for estate planning.',
    assignedTo: 'Courtney K.',
    createdAt: '2026-06-15',
    updatedAt: '2026-06-28',
    age: 52,
    state: 'CA',
    city: 'Los Angeles',
  },
  {
    id: 'l6',
    firstName: 'Patricia',
    lastName: 'Miller',
    email: 'pmiller@email.com',
    phone: '(555) 789-0123',
    status: 'closed_won',
    source: 'Facebook Ad',
    tags: ['final_expense'],
    notes: 'Closed! Issued FE policy with Americo.',
    assignedTo: 'Courtney K.',
    createdAt: '2026-06-10',
    updatedAt: '2026-06-26',
    age: 65,
    state: 'TX',
    city: 'Dallas',
  },
];

export const mockClients: Client[] = [
  {
    id: 'c1',
    firstName: 'Patricia',
    lastName: 'Miller',
    email: 'pmiller@email.com',
    phone: '(555) 789-0123',
    dob: '1961-03-15',
    address: '1234 Oak St',
    city: 'Dallas',
    state: 'TX',
    zip: '75201',
    beneficiaries: [
      { id: 'b1', name: 'John Miller', relationship: 'Spouse', percentage: 100 },
    ],
    existingCoverage: 'Group life through employer ($25,000)',
    medicalNotes: 'Type 2 diabetes, controlled. No tobacco.',
    createdAt: '2026-06-26',
    policies: ['p1'],
  },
  {
    id: 'c2',
    firstName: 'Henry',
    lastName: 'Thompson',
    email: 'hthompson@email.com',
    phone: '(555) 890-1234',
    dob: '1955-07-22',
    address: '567 Maple Ave',
    city: 'Nashville',
    state: 'TN',
    zip: '37201',
    beneficiaries: [
      { id: 'b2', name: 'Susan Thompson', relationship: 'Spouse', percentage: 60 },
      { id: 'b3', name: 'David Thompson', relationship: 'Son', percentage: 40 },
    ],
    existingCoverage: 'None',
    medicalNotes: 'Hypertension, on medication. Former smoker (quit 2019).',
    createdAt: '2026-05-14',
    policies: ['p2'],
  },
];

export const mockPolicies: Policy[] = [
  {
    id: 'p1',
    clientId: 'c1',
    clientName: 'Patricia Miller',
    type: 'final_expense',
    carrier: 'Americo',
    policyNumber: 'AME-2026-004821',
    faceAmount: 15000,
    premium: 89.50,
    commission: 537.00,
    commissionRate: 0.75,
    status: 'active',
    effectiveDate: '2026-07-01',
    issueDate: '2026-06-26',
    notes: 'Level benefit. No exam required.',
  },
  {
    id: 'p2',
    clientId: 'c2',
    clientName: 'Henry Thompson',
    type: 'final_expense',
    carrier: 'Mutual of Omaha',
    policyNumber: 'MOO-2026-119342',
    faceAmount: 20000,
    premium: 142.00,
    commission: 994.00,
    commissionRate: 0.85,
    status: 'active',
    effectiveDate: '2026-06-01',
    issueDate: '2026-05-14',
    notes: 'Graded benefit first 2 years.',
  },
  {
    id: 'p3',
    clientId: 'c1',
    clientName: 'James Chen',
    type: 'mortgage_protection',
    carrier: 'Corebridge',
    policyNumber: 'CB-2026-008891',
    faceAmount: 285000,
    premium: 198.00,
    commission: 1386.00,
    commissionRate: 0.90,
    status: 'pending',
    effectiveDate: '2026-07-15',
    issueDate: '2026-06-28',
    notes: 'Return of premium rider added.',
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: 'a1',
    leadId: 'l1',
    title: 'Robert Johnson - FE Consultation',
    description: 'Discuss Final Expense options and pricing',
    startTime: '2026-06-29T10:00:00',
    endTime: '2026-06-29T11:00:00',
    type: 'phone',
    status: 'scheduled',
  },
  {
    id: 'a2',
    leadId: 'l2',
    title: 'Maria Santos - MP Review',
    description: 'Present mortgage protection proposal',
    startTime: '2026-06-29T14:00:00',
    endTime: '2026-06-29T15:00:00',
    type: 'video',
    status: 'scheduled',
  },
  {
    id: 'a3',
    leadId: 'l5',
    title: 'Michael Davis - Whole Life',
    description: 'Final review of whole life proposal',
    startTime: '2026-06-29T16:30:00',
    endTime: '2026-06-29T17:30:00',
    type: 'in_person',
    status: 'scheduled',
  },
  {
    id: 'a4',
    clientId: 'c1',
    title: 'Patricia Miller - Policy Delivery',
    description: 'Deliver policy documents and collect first premium',
    startTime: '2026-06-30T11:00:00',
    endTime: '2026-06-30T12:00:00',
    type: 'in_person',
    status: 'scheduled',
  },
  {
    id: 'a5',
    leadId: 'l4',
    title: 'Dorothy Brown - FE Quote',
    description: 'Go over FE options on fixed income',
    startTime: '2026-06-30T13:00:00',
    endTime: '2026-06-30T14:00:00',
    type: 'phone',
    status: 'scheduled',
  },
];

export const mockTasks: Task[] = [
  {
    id: 't1',
    title: 'Follow up with Robert Johnson',
    description: 'Send quote comparison from Americo vs Mutual of Omaha',
    dueDate: '2026-06-30',
    priority: 'high',
    completed: false,
    relatedTo: 'l1',
    relatedType: 'lead',
    createdAt: '2026-06-28',
  },
  {
    id: 't2',
    title: 'Submit Patricia Miller application',
    description: 'Upload signed application to Americo portal',
    dueDate: '2026-06-29',
    priority: 'urgent',
    completed: false,
    relatedTo: 'c1',
    relatedType: 'client',
    createdAt: '2026-06-26',
  },
  {
    id: 't3',
    title: 'Order medical records - Henry Thompson',
    description: 'Request APS from Dr. Williams office',
    dueDate: '2026-07-02',
    priority: 'medium',
    completed: false,
    relatedTo: 'c2',
    relatedType: 'client',
    createdAt: '2026-06-27',
  },
  {
    id: 't4',
    title: 'Call new Facebook leads',
    description: 'Batch outreach to 8 new leads from this week campaign',
    dueDate: '2026-06-29',
    priority: 'high',
    completed: false,
    createdAt: '2026-06-28',
  },
  {
    id: 't5',
    title: 'Review Corebridge commission statement',
    description: 'Reconcile May commissions against agency records',
    dueDate: '2026-07-05',
    priority: 'medium',
    completed: true,
    createdAt: '2026-06-20',
  },
];

export const mockCarriers: Carrier[] = [
  {
    id: 'car1',
    name: 'Americo',
    contactName: 'Tom Richards',
    contactEmail: 'trichards@americo.com',
    contactPhone: '(800) 555-0101',
    website: 'americo.com',
    products: ['final_expense', 'whole_life'],
    notes: 'Strong FE product. Quick issue. No exam up to $30k.',
    activeContracts: 8,
  },
  {
    id: 'car2',
    name: 'Mutual of Omaha',
    contactName: 'Lisa Park',
    contactEmail: 'lpark@mutualofomaha.com',
    contactPhone: '(800) 555-0202',
    website: 'mutualofomaha.com',
    products: ['final_expense', 'term', 'whole_life'],
    notes: 'Top FE carrier. Living Whole Life product excellent.',
    activeContracts: 12,
  },
  {
    id: 'car3',
    name: 'Corebridge',
    contactName: 'David Chen',
    contactEmail: 'dchen@corebridge.com',
    contactPhone: '(800) 555-0303',
    website: 'corebridgefinancial.com',
    products: ['mortgage_protection', 'term', 'universal_life'],
    notes: 'Great MP and term products. Formerly AIG Life.',
    activeContracts: 6,
  },
  {
    id: 'car4',
    name: 'Transamerica',
    contactName: 'Sarah West',
    contactEmail: 'swest@transamerica.com',
    contactPhone: '(800) 555-0404',
    website: 'transamerica.com',
    products: ['final_expense', 'term', 'whole_life', 'universal_life'],
    notes: 'Good rates on term. FE product competitive.',
    activeContracts: 5,
  },
  {
    id: 'car5',
    name: 'Royal Neighbors',
    contactName: 'Mike Johnson',
    contactEmail: 'mjohnson@royalneighbors.org',
    contactPhone: '(800) 555-0505',
    website: 'royalneighbors.org',
    products: ['final_expense', 'whole_life'],
    notes: 'Fraternal carrier. Good for graded benefit cases.',
    activeContracts: 3,
  },
  {
    id: 'car6',
    name: 'United Home Life',
    contactName: 'Carol Adams',
    contactEmail: 'cadams@uhlins.com',
    contactPhone: '(800) 555-0606',
    website: 'unitedHomeLife.com',
    products: ['final_expense'],
    notes: 'Simplified issue. Good for impaired risk cases.',
    activeContracts: 4,
  },
];

export const mockCommissions: Commission[] = [
  {
    id: 'com1',
    policyId: 'p1',
    policyNumber: 'AME-2026-004821',
    clientName: 'Patricia Miller',
    carrier: 'Americo',
    type: 'final_expense',
    amount: 537.00,
    status: 'paid',
    paidDate: '2026-06-28',
    month: '2026-06',
  },
  {
    id: 'com2',
    policyId: 'p2',
    policyNumber: 'MOO-2026-119342',
    clientName: 'Henry Thompson',
    carrier: 'Mutual of Omaha',
    type: 'final_expense',
    amount: 994.00,
    status: 'paid',
    paidDate: '2026-06-15',
    month: '2026-06',
  },
  {
    id: 'com3',
    policyId: 'p3',
    policyNumber: 'CB-2026-008891',
    clientName: 'James Chen',
    carrier: 'Corebridge',
    type: 'mortgage_protection',
    amount: 1386.00,
    status: 'pending',
    month: '2026-06',
  },
  {
    id: 'com4',
    policyId: 'p4',
    policyNumber: 'AME-2026-004756',
    clientName: 'Ruth Garcia',
    carrier: 'Americo',
    type: 'final_expense',
    amount: 643.00,
    status: 'paid',
    paidDate: '2026-06-10',
    month: '2026-06',
  },
  {
    id: 'com5',
    policyId: 'p5',
    policyNumber: 'MOO-2026-118801',
    clientName: 'Frank Wilson',
    carrier: 'Mutual of Omaha',
    type: 'whole_life',
    amount: 2100.00,
    status: 'paid',
    paidDate: '2026-05-28',
    month: '2026-05',
  },
];

export const recentActivity = [
  { id: 'ra1', type: 'policy', text: 'New policy issued — Patricia Miller (Americo FE $15k)', time: '2 hours ago' },
  { id: 'ra2', type: 'lead', text: 'New lead from Facebook — James Williams', time: '4 hours ago' },
  { id: 'ra3', type: 'appointment', text: 'Appointment completed — Maria Santos', time: '6 hours ago' },
  { id: 'ra4', type: 'commission', text: 'Commission received — $994 from Mutual of Omaha', time: '1 day ago' },
  { id: 'ra5', type: 'task', text: 'Task completed — Submit Henry Thompson application', time: '1 day ago' },
  { id: 'ra6', type: 'lead', text: 'Lead status updated — Michael Davis → Negotiation', time: '2 days ago' },
];
